apiVersion: v1
kind: Service
metadata:
  name: crawler-service
spec:
  selector:
    app: synergychat-crawler
  type: ClusterIP
  ports:
    - protocol: TCP
      # crawler-service:80
      port: 80
      # forward to pod `8080`
      targetPort: 8080
