name: diamol-ch16-package-staging-windows

on:
  # push:
  #   paths:
  #     - ".github/workflows/diamol-ch16-package-staging-windows.yaml"
  # workflow_run:
  #   workflows: [diamol-ch16-package-staging]
  #   types: [completed]
  #   branches:
  #     - "main"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository_owner }}
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  package-windows:
    runs-on: windows-2022
    if: ${{ github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: GHCR login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-push
        working-directory: labs/00-docker/diamol/ch16/cicd
        run: ./build-push.ps1
        shell: pwsh
        env:
          BUILD_ID: ${{ github.workflow_ref }}
          COMMIT_SHA: ${{ github.sha	}}
      - name: push-staging
        working-directory: labs/00-docker/diamol/ch16/cicd
        run: ./tag-push.ps1 -From build -To staging
        shell: pwsh
    permissions:
      contents: read
      packages: write
