{
 "title": "Annotations & Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "created tasks number",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "todo_tasks_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "received HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "in-progress HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 0 },
   "targets": [
    { "expr": "http_requests_in_progress", "legendFormat": "__auto" }
   ]
  }
 ]
}