name: diamol-ch16-smoke-test

on:
  push:
    paths:
      - ".github/workflows/diamol-ch16-smoke-test.yaml"
      - "labs/00-docker/diamol/ch16/cicd/smoke-test.ps1"
      - "labs/00-docker/diamol/ch16/cicd/set-vars.ps1"
      - "labs/00-docker/diamol/ch16/src/docker-compose*.yml"
  workflow_run:
    workflows: [diamol-ch16-package-staging]
    types: [completed]
    branches:
      - "main"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.repository_owner }}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' ||
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v6
      - name: GHCR login
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: smoke-test
        working-directory: labs/00-docker/diamol/ch16/cicd
        run: ./smoke-test.ps1
        shell: pwsh
